# Generated by Django 5.2.6 on 2026-05-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grupo_monitores'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='whatsapp_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
