# Generated by Django 5.2.6 on 2026-05-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grupo_whatsapp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
